from flaskshop import db
from flaskshop.models import Clothing
#----- Name, colour, brand, size, price, clothing_category, sub_category, gender, image_file, colour_two, image_two-----
db.create_all()
def init_db():
    a = Clothing(name='Abercrombie-&-Fitch-logo-cuffed-jogger', colour='Grey', brand='Abercrombie-&-Fitch', size='male_clothing', price=58.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Male', image_file='af_men_cuff_gray', colour_two='navy', image_two='af_men_cuff_jog', colour_three=None, image_three = None)
    b = Clothing(name='Abercrombie-&-Fitch-slim-fit-jogger', colour='Light Grey', brand='Abercrombie-&-Fitch', size='female_clothing', price=56.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Female', image_file='af_w_slim_jog', colour_two=None, colour_three=None, image_two=None, image_three=None)
    c = Clothing(name='Abercrombie-&-Fitch-icon-logo-print-crewneck-sweatshirt', colour='Navy', brand='Abercrombie-&-Fitch', size='male_clothing', price=48.00, clothing_category='Tops', sub_category='Sweatshirts', gender='Male', image_file='af_crew_men', colour_two=None, colour_three=None, image_two=None, image_three=None)
    d = Clothing(name='Adidas-Originals-Embroidered-logo-beanie', colour='Orange', brand='Adidas', size='one_size', price=18.00, clothing_category='Accessories', sub_category='Hats', gender='Mixed', image_file='ad_orng_beanie', colour_two=None, colour_three=None, image_two=None, image_three=None)
    e = Clothing(name='Adidas-Originals-three-stripe-track-pants', colour='Black', brand='Adidas', size='female_clothing', price=45.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Female', image_file='ad_stripe_w', colour_two=None, colour_three=None, image_two=None, image_three=None)
    f = Clothing(name='Adidas-Originals-three-stripe-track-pants', colour='Black', brand='Adidas', size='male_clothing', price=45.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Male', image_file='ad_stripe_m', colour_two=None, colour_three=None, image_two=None, image_three=None)
    g = Clothing(name='Adidas-Originals-swift-running-trainers', colour='White', brand='Adidas', size='female_footwear', price=70.00, clothing_category='Shoes', sub_category='Trainers', gender='Female', image_file='ad_swift_white', colour_two=None, colour_three=None, image_two=None, image_three=None)
    h = Clothing(name='Adidas-Originals-2-pack-of-socks', colour='Red', brand ='Adidas', size='male_accessories', price=7.50, clothing_category='Accessories', sub_category='Socks', gender='Mixed', image_file='ad_socks', colour_two=None, colour_three=None, image_two=None, image_three=None)
    i = Clothing(name='Adidas-running-arm-band', colour='Black', brand ='Adidas', size='one_size', price=18.99, clothing_category='Accessories', sub_category='Sports', gender='Mixed', image_file='ad_arm_band', colour_two=None, colour_three=None, image_two=None, image_three=None)
    j = Clothing(name='Adidas-Skyline-silicon-watch', colour='Green', brand ='Adidas', size='one_size', price=60.00, clothing_category='Accessories', sub_category='Jewellery', gender='Mixed', image_file='ad_watch', colour_two=None, colour_three=None, image_two=None, image_three=None)
    k = Clothing(name='Adidas-Yung-1-trainers', colour='White', brand='Adidas', size='female_footwear', price=110.00, clothing_category='Shoes', sub_category='Trainers', gender='Female', image_file='ad_yung', colour_two=None, colour_three=None, image_two=None, image_three=None)
    l = Clothing(name='Calvin-Klein-icon-logo-leggings', colour='Light Grey', brand='Calvin-Klein', size='female_clothing', price=18.00, clothing_category='Bottoms', sub_category='Leggings', gender='Female', image_file='ck_leg_grey', colour_two='Black', image_two='ck_leg_black', colour_three=None, image_three=None)
    m = Clothing(name='Calvin-Klein-baseball-cap', colour='Black', brand='Calvin-Klein', size='one_size', price=12.00, clothing_category='Accessories', sub_category='Hats', gender='Mixed', image_file='ck_cap', colour_two=None, colour_three=None, image_two=None, image_three=None)
    n = Clothing(name='Calvin-Klein-hoodie', colour='Navy', brand='Calvin-Klein', size='male_clothing', price=75.00, clothing_category='Tops', sub_category='Hoodies', gender='Male', image_file='ck_hoodie', colour_two=None, colour_three=None, image_two=None, image_three=None)
    o = Clothing(name='Champion-oversized-TShirt', colour='Light Grey', brand='Champion', size='female_clothing', price=35.00, clothing_category='Tops', sub_category='T-Shirts', gender='Female', image_file='champ_t', colour_two=None, colour_three=None, image_two=None, image_three=None)
    p = Clothing(name='Champion-hooded-puffer-jacket', colour='Navy', brand='Champion', size='male_clothing', price=165.00, clothing_category='Outerwear', sub_category='Jackets', gender='Male', image_file='champ_puff_navy', colour_two='Yellow', image_two='champ_puff_yellow', colour_three=None, image_three=None)
    q = Clothing(name='Champion-retro-tracksuit-top', colour='Multi', brand='Champion', size='female_clothing', price=90.00, clothing_category='Outerwear', sub_category='Tracksuit-Tops', gender='Female', image_file='champ_track_top', colour_two=None, colour_three=None, image_two=None, image_three=None)
    r = Clothing(name='Ellesse-relaxed-fleece-with-colour-block-stripe', colour='Yellow', brand='Ellesse', size='female_clothing', price= 50.00, clothing_category='Outerwear', sub_category='Tracksuit-Tops', gender='Female', image_file='ellesse_sweat', colour_two=None, colour_three=None, image_two=None, image_three=None)
    s = Clothing(name='Ellesse-relaxed-TShirt-with-chest-logo', colour='Burgandy', brand='Ellesse', size='female_clothing', price=25.00, clothing_category='Tops', sub_category='T-Shirts', gender='Female', image_file='ellesse_t', colour_two=None, colour_three=None, image_two=None, image_three=None)
    t = Clothing(name='Fila-boyfriend-hoodie', colour='Burgandy', brand='Fila', size='female_clothing', price=55.00, clothing_category='Tops', sub_category='Hoodies', gender='Female', image_file='fila_hoodie_w', colour_two=None, colour_three=None, image_two=None, image_three=None)
    u = Clothing(name='Fila-disruptor-III', colour='White', brand='Fila', size='mixed_footwear', price=79.00, clothing_category='Shoes', sub_category='Trainers', gender='Mixed', image_file='disruptors', colour_two=None, colour_three=None, image_two=None, image_three=None)
    v = Clothing(name='Fila-ringer-TShirt', colour='White', brand='Fila', size='male_clothing', price=23.00, clothing_category='Tops', sub_category='T-Shirts', gender='Male', image_file='fila_t', colour_two=None, colour_three=None, image_two=None, image_three=None)
    w = Clothing(name='Fila-windbreaker-jacket', colour='Multi', brand='Fila', size='male_clothing', price=55.00, clothing_category='Outerwear', sub_category='Tracksuit-Tops', gender='Male', image_file='fila_windbreak', colour_two=None, colour_three=None, image_two=None, image_three=None)
    x = Clothing(name='Ivy-Park-mesh-panel-leggings', colour='Black', brand='Ivy-Park', size='female_clothing', price=65.00, clothing_category='Bottoms', sub_category='Leggings', gender='Female', image_file='ivy_leggs', colour_two=None, colour_three=None, image_two=None, image_three=None)
    y = Clothing(name='Ivy-Park-logo-Sweatpants', colour='Yellow', brand='Ivy-Park', size='female_clothing', price=45.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Female', image_file='ivy_jogs', colour_two=None, colour_three=None, image_two=None, image_three=None)
    z = Clothing(name='Nike-mini-backpack', colour='Black', brand='Nike', size='one_size', price=15.00 , clothing_category='Accessories', sub_category='Bags', gender='Mixed', image_file='nike_mini_back', colour_two=None, colour_three=None, image_two=None, image_three=None)
    aa = Clothing(name='Nike-cuffed-jogger', colour='Grey', brand='Nike', size='male_clothing', price=38.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Male', image_file='nike_jogs_grey', colour_two='Navy', image_two='nike_jogs_navy', colour_three='Black', image_three='nike_jogs_black')
    bb = Clothing(name='Nike-Pro-training-crossover-leggings', colour='Black', brand='Nike', size='female_clothing', price=38.00, clothing_category='Bottoms', sub_category='Leggings', gender='Female', image_file='nike_training_leggs', colour_two=None, colour_three=None, image_two=None, image_three=None)
    cc = Clothing(name='Nike-hermitage-bumbag', colour='Black', brand='Nike', size='one_size', price=17.00, clothing_category='Accessories', sub_category='Bags', gender='Mixed', image_file='nike_bum_bag', colour_two=None, colour_three=None, image_two=None, image_three=None)
    dd = Clothing(name='Nike-Swoosh-sandals', colour='Black', brand='Nike', size='male_footwear', price=18.00, clothing_category='Shoes', sub_category='Sandals', gender='Male', image_file='nike_sandals', colour_two=None, colour_three=None, image_two=None, image_three=None)
    ee = Clothing(name='Puma-training-EvoStripe-hoodie', colour='Grey', brand='Puma', size='male_clothing', price=45.00, clothing_category='Outerwear', sub_category='Tracksuit-Tops', gender='Male', image_file='puma_fleece', colour_two=None, colour_three=None, image_two=None, image_three=None)
    ff = Clothing(name='Puma-training-EvoStripe-bottoms', colour='Grey', brand='Puma', size='male_clothing', price=60.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Male', image_file='puma_pants', colour_two=None, colour_three=None, image_two=None, image_three=None)
    gg = Clothing(name='Puma-runnning-ignite-unrest-trainers', colour='Khaki', brand='Puma', size='male_footwear', price=85.00, clothing_category='Shoes', sub_category='Trainers', gender='Male', image_file='puma_trainers', colour_two=None, colour_three=None, image_two=None, image_three=None)
    hh = Clothing(name='Puma-thunder-trainers', colour='Green', brand='Puma', size='female_footwear', price=110.00, clothing_category='Shoes', sub_category='Trainers', gender='Female', image_file='puma_w_trainers', colour_two=None, colour_three=None, image_two=None, image_three=None)
    ii = Clothing(name='Puma-organic-cotton-mustard-boxy-tee', colour='Yellow', brand='Puma', size='female_clothing', price=22.00, clothing_category='Tops', sub_category='T-Shirts', gender='Female', image_file='puma_t', colour_two=None, colour_three=None, image_two=None, image_three=None)
    jj = Clothing(name='Stussy-bralet-with-logo-taping', colour='Camo', brand='Stussy', size='female_clothing', price=35.00, clothing_category='Tops', sub_category='T-Shirts', gender='Female', image_file='stussy_bralet', colour_two=None, colour_three=None, image_two=None, image_three=None)
    kk = Clothing(name='Stussy-shadow-logo-beanie', colour='Pink', brand='Stussy', size='one_size', price=34.00, clothing_category='Accessories', sub_category='Hats', gender='Mixed', image_file='stussy_beanie', colour_two=None, colour_three=None, image_two=None, image_three=None)
    ll = Clothing(name='GymShark-solace-bottoms', colour='Blue', brand='GymShark', size='female_clothing', price=30.00, clothing_category='Bottoms', sub_category='Sweatpants', gender='Female', image_file='gymshark_jogs', colour_two=None, colour_three=None, image_two=None, image_three=None)
    mm = Clothing(name='GymShark-Sloungeleggings', colour='Pink', brand='GymShark', size='female_clothing', price=25.00, clothing_category='Bottoms', sub_category='Leggings', gender='Female', image_file='slounge_leggs', colour_two=None, colour_three=None, image_two=None, image_three=None)
    nn = Clothing(name='GymShark-Slounge-hoodie', colour='Pink', brand='GymShark', size='female_clothing', price=20.00, clothing_category='Tops', sub_category='Hoodies', gender='Female', image_file='slounge_hoodie', colour_two=None, colour_three=None, image_two=None, image_three=None)
    oo = Clothing(name='Calvin-Klein-socks', colour='Red', brand='Calvin-Klein', size='male_accessories', price=8.00, clothing_category='Accessories', sub_category='Socks', gender='Mixed', image_file='ck_socks', colour_two=None, colour_three=None, image_two=None, image_three=None)

    db.session.add(a)
    db.session.add(b)
    db.session.add(c)
    db.session.add(d)
    db.session.add(e)
    db.session.add(f)
    db.session.add(g)
    db.session.add(h)
    db.session.add(i)
    db.session.add(j)
    db.session.add(k)
    db.session.add(l)
    db.session.add(m)
    db.session.add(n)
    db.session.add(o)
    db.session.add(p)
    db.session.add(q)
    db.session.add(r)
    db.session.add(s)
    db.session.add(t)
    db.session.add(u)
    db.session.add(v)
    db.session.add(w)
    db.session.add(x)
    db.session.add(y)
    db.session.add(z)
    db.session.add(aa)
    db.session.add(bb)
    db.session.add(cc)
    db.session.add(dd)
    db.session.add(ee)
    db.session.add(ff)
    db.session.add(gg)
    db.session.add(hh)
    db.session.add(ii)
    db.session.add(jj)
    db.session.add(kk)
    db.session.add(ll)
    db.session.add(mm)
    db.session.add(nn)
    db.session.add(oo)
    db.session.commit()

if __name__=='__main__':
    init_db()
